version: '3'

services:

  api_service:
    build:
        context: .
        dockerfile: dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mySql:3306/ppAssemblyLineBa
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ppAssemblyLineBa'
    ports:
      - "3306:3306"
