version: '3'

services:

  mysql:
    image: 'mysql:8.0'
    container_name: 'paragonPioneerBeDatabase'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ppAssemblyLineBa'
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "3306:3306"
