version: '3'

services:

  mariadb:
    image: 'mariadb:10.6'
    container_name: 'paragonPioneerBeDatabase'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ppAssemblyLineBa'
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "3306:3306"