steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west10-docker.pkg.dev/dxd-ai-poc/paragon-sql-images/paragon-sql:latest','.docker/databaseService', '.' ]

images:
  - 'europe-west10-docker.pkg.dev/dxd-ai-poc/paragon-sql-images/paragon-sql:latest'