name: Update Database

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    environment:
      name: stage

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run Database in Container
        run: |
          # Export Environment Variables
          export MYSQL_ROOT_PASSWORD=$'{{ secrets.MYSQL_ROOT_PASSWORD }}'
          export MYSQL_DATABASE=$'{{ secrets.MYSQL_DATABASE }}'
          export MYSQL_USER=$'{{ secrets.MYSQL_USER }}'
          export MYSQL_PASSWORD=$'{{ secrets.MYSQL_USER_PASSWORD }}'
          
          docker compose up -d
          
          sleep 20

      - name: Populate database
        run: |
          mysql  \
          -u MYSQL_USER \
          -p ${{ secrets.MYSQL_USER_PASSWORD }} 
          {{ secrets.MYSQL_DATABASE }} < .docker/dump/database-insert.sql

      - name: Dump Database
        run: |
          export DUMP_FILE_NAME= (date +'%Y-%m-%d-%H-%M-%S')-dump.sql
          docker exec paragonPioneerBeDatabase-dev \
          mysqldump \
          -u root 
          --password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          $MYSQL_DATABASE > $DUMP_FILE_NAME

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Check out
        run: echo "Production deployment not implemented yet"