name: Update Database

on:
  push:
    branches: [ "main", "develop" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: stage

    steps:
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Trigger Cloud Build
      run: gcloud builds submit --config .cloudbuilds/cloudbuild-mysql.yaml .